### ISSUE TITLE
ChartJS Issue When using readme

### ISSUE THREAD

**Issue by paytah232** [bbsnly/chartjs-php#46]
**Describe the bug**
Copy and pasting the readme leads to empty chart

**To Reproduce**
Steps to reproduce the bug:

1. Copying the readme in:
```
<?php
    $page_title = 'Chart';
    require_once '../includes/load.php';
    // Checkin What level user has permission to view this page
    page_require_group('User');
    // Pull in chart package
    use Bbsnly\ChartJs\Chart;
    use Bbsnly\ChartJs\Config\Data;
    use Bbsnly\ChartJs\Config\Dataset;
    use Bbsnly\ChartJs\Config\Options;
    // Get Info
    $chart = new Chart;
    $chart->type = 'line';

    $data = new Data();
    $data->labels = ['Red', 'Green', 'Blue'];

    $dataset = new Dataset();
    $dataset->data = [5, 10, 20];
    $data->datasets[] = $dataset->data;

    $chart->data($data);

    $options = new Options();
    $options->responsive = true;
    $chart->options($options);
    //$chart->get(); // Returns the array of chart data
    //$chart->toJson(); // Returns the JSON representation of the chart data
    //$chart->toHtml('my_chart'); // Returns the HTML and JavaScript code for the chart
    // Formatting
    include_once '../layouts/header.php';
?>
<script src="<?php echo BASE_URL; ?>/libs/js/chart.js"></script><!-- Equiv to 4.4.7-->
<div><?php echo $chart->toHtml('my_chart'); ?></div>
```

2. Gets the following error:
```
Uncaught TypeError: Cannot convert undefined or null to object
    at fill (<anonymous>)
    at VM4190 chart.js:19:21498
    at VM4190 chart.js:19:21562
    at VM4190 chart.js:19:21914
    at qe (VM4190 chart.js:19:22658)
    at Object.get (VM4190 chart.js:19:21208)
    at LineController.initialize (VM4190 chart.js:19:50417)
    at LineController.initialize (VM4190 chart.js:19:120686)
    at new Ns (VM4190 chart.js:19:50273)
    at new LineController (VM4190 chart.js:19:120408)
```

4. The output from toHtml was:
```
<canvas id="my_chart"></canvas>
        <script>
            new Chart(
                document.getElementById("my_chart").getContext("2d"),
                {"type":"line","data":{"labels":["Red","Green","Blue"],"datasets":[[5,10,20]]},"options":{"responsive":true}}
            );
        </script>
```

**Expected behavior**
A chart with the basic data set should appear.

**Actual behavior**
ChartJS error

**Additional context**
Running on:
PHP - 8.2.21
chartjs-php - 4.0.1
Chart.js - 4.4.7

**Comment by bbsnly** [comment]
Thank you for reporting the bug @paytah232. I will get back to you as soon as I have an update.

**Comment by bbsnly** [comment]
Hello @paytah232. Since ChartJS v4, they strictly expect the dataset to be an object, and that is where the issue seems to be. I am working on a bug fix. I'll keep you posted.

**Comment by bbsnly** [comment]
@paytah232, I fixed the example in the Readme file. It was outdated and worked with ChartJS v2 and v3 but not v4.

Instead of `$data->datasets[] = $dataset->data;` you must use `$data->datasets[] = $dataset;` to ensure the whole object is used.

**Comment by paytah232** [comment]
@bbsnly - Thanks for the fix. Worked like a charm!
